set ROOT_DIR=%~dp0
set SOURCE_DIR=%ROOT_DIR%
set BUILD_DIR=%ROOT_DIR%buildx64

cmake -S %SOURCE_DIR% -B %BUILD_DIR% ^
    -DCMAKE_RUNTIME_OUTPUT_DIRECTORY="%BUILD_DIR%\output\bin" ^
    -DCMAKE_LIBRARY_OUTPUT_DIRECTORY="%BUILD_DIR%\output\bin" ^
    -DCMAKE_ARCHIVE_OUTPUT_DIRECTORY="%BUILD_DIR%\output\lib"